POST localhost:752/api/google
Content-Type: application/json

{
  "coords": "K3",
  "value": "Hello"
}

###
GET http://localhost:752/api/google/
Content-Type: application/json

{
  "coords": "J1:J10"
}

###
GET http://localhost:752/api/google/name
Content-Type: application/json

{
  "coords": "r1c1",
  "name": "АО «Волгогаз»"
}

###
PUT http://localhost:752/api/google
Content-Type: application/json

{
  "pf_number": "ПФ-86.0317/22",
  "object_name": "Подземный газопровод",
  "tech_object_number": "б/н",
  "factory_object_number": "б/н",
  "registration_object_number": "б/н",
  "location": "г.Обнинск., Московская 33/10",
  "customer_name": "АО «Газпром газораспределение Обнинск» от 12.04.2022г.",
  "date_registration": "05.05.2022",
  "full_name": "Дортман Е."
}

