POST localhost:752/api/google
Content-Type: application/json

{
  "coords": "K3",
  "value": "Hello"
}
###
GET http://localhost:752/api/google
Content-Type: application/json

{
  "coords": "J1:J10"
}
###
PUT http://localhost:752/api/google
Content-Type: application/json

{
  "prefix": "ДОК",
  "date_registration": "18.03.2022",
  "document_id": "ДОК-00001/ГГ",
  "date_control": "18.03.2022",
  "name_object0": "Котел",
  "object_number_tech": "б/н",
  "object_number_factory": "-",
  "object_number_registration": "-",
  "customer_name": "НБ 1, ТН Порт Приморск"
}
###
