POST localhost:752/api/hubex/task_create
#POST 77.87.86.242:8001/api/hubex/task_create
Content-Type: application/json

{
  "TenantID": 46,
  "TaskID": 1315,
  "AssetID": 2692,
  "TaskConversationID": null,
  "TenantMemberID": null,
  "AccountID": null,
  "UserID": null,
  "CompanyID": null,
  "EventID": 3,
  "TaskStageID": null
}